### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by sbckr**

### CODE REVIEW

**Review by strieflin — DISMISSED** [review]
LGTM

**Comment by sbckr** [comment]
cannot tell reasons for the codecov check to fail, but its own report sais coverage has increased:


> # [Codecov](https://codecov.io/gh/carbynestack/castor/pull/48?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=carbynestack) Report
> 
> > Merging [#48](https://codecov.io/gh/carbynestack/castor/pull/48?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=carbynestack) ([edc36a7](https://github.com/carbynestack/castor/commit/edc36a766cf8c678d234e022111ec2ae780e1aec)) into [master](https://codecov.io/gh/carbynestack/castor/commit/17212293c1e426e1303a5f8cabca988556a8f65e?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=carbynestack) ([1721229](https://github.com/carbynestack/castor/commit/17212293c1e426e1303a5f8cabca988556a8f65e)) will **increase** coverage by `57.14%`.
> > The diff coverage is `0.00%`.
>

**Review by strieflin — DISMISSED** [review]
LGTM

**Review by strieflin — APPROVED** [review]
LGTM

**Pull request merged**
