### PR TITLE
chore: release  chart 0.3.0

### PR DESCRIPTION
**Pull request by cs-minion**
:package: Staging a new release
---

### Features

* **charts:** add redis reservationTimeout ([#63](https://github.com/carbynestack/castor/issues/63)) ([eead173](https://github.com/carbynestack/castor/commit/eead173d1c28d51dff3aa677f76da2cd74bc81c2))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by sbckr — APPROVED** [review]
LGTM

**Review by sbckr — APPROVED** [review]
LGTM

**Review by sbckr — APPROVED** [review]
LGTM

**Comment by cs-minion** [comment]
:robot: Release is at https://github.com/carbynestack/castor/releases/tag/chart-v0.3.0 :sunflower:

**Pull request merged**
